#! /bin/bash

if [[ $1 == "deploy" ]]
then
   docker build -t arava-admin . || exit 1
   docker tag arava-admin registry.ndogga.com/arava/arava-admin:latest || exit 1
   docker push registry.ndogga.com/arava/arava-admin:latest || exit 1
   curl -X POST https://portainer.ndogga.com/api/webhooks/342fec7a-fe32-4ae4-9c06-06c0f6027fbb
   echo "Successfully built and deployed to Portainer"
   exit 0
fi

echo "Available commands : deploy"
exit 1