#! /bin/bash

if [[ $1 == "deploy" ]]
then
   docker build -t arava-admin . || exit 1
   docker tag arava-admin registry.ndogga.com/arava/arava-admin:latest || exit 1
   docker push registry.ndogga.com/arava/arava-admin:latest || exit 1
   curl -X POST https://portainer.ndogga.io/api/webhooks/fa92c7dc-8f1e-4fda-a275-ead3a12fca3e
   echo "Successfully built and deployed to Portainer"
   exit 0
fi

echo "Available commands : deploy"
exit 1